sudo: false
language: node_js
node_js:
  - '4'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass --version "=3.4.20"'
  - 'gem install compass --version "=1.0.3"'
script:
  - 'npm test'
